name: M3S07 Java Install with Maven

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Clean and Install with Maven M3S07-Docker
        run: |
          cd M3S07-Docker
          mvn clean install
